# Generated by Django 6.0.3 on 2026-03-07 17:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categora', models.CharField(choices=[('GT3', 'GT3'), ('PCUP', 'PCUP')], max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='foto/%Y/%m/%d')),
                ('publicado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_config', models.CharField(choices=[('QUALY_SAFE', 'QUALY_SAFE'), ('QUALY', 'QUALY'), ('QUALY_RAIN', 'QUALY_RAIN'), ('RACE_SAFE', 'RACE_SAFE'), ('RACE', 'RACE'), ('RACE_RAIN', 'RACE_RAIN')], max_length=100)),
                ('arquivo', models.FileField(blank=True, upload_to='setups/%Y/%m/')),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='catalogo.carro')),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.pista')),
            ],
        ),
    ]
