# Generated by Django 6.0.3 on 2026-03-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='categora',
            new_name='categoria',
        ),
    ]
