# Generated by Django 6.0.3 on 2026-03-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_rename_categora_carro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pista',
            name='foto',
            field=models.ImageField(blank=True, upload_to='foto/%Y/%m/%d'),
        ),
    ]
