# Generated by Django 6.0.3 on 2026-03-09 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_pista_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='pista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='catalogo.pista'),
        ),
    ]
