# Generated by Django 6.0.3 on 2026-03-12 13:15

import catalogo.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_setup_pista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='nome_config',
        ),
        migrations.AddField(
            model_name='setup',
            name='config_qualy',
            field=models.FileField(blank=True, null=True, upload_to=catalogo.models.upload_setup_path),
        ),
        migrations.AddField(
            model_name='setup',
            name='config_qualy_rain',
            field=models.FileField(blank=True, null=True, upload_to=catalogo.models.upload_setup_path),
        ),
        migrations.AddField(
            model_name='setup',
            name='config_qualy_safe',
            field=models.FileField(blank=True, null=True, upload_to=catalogo.models.upload_setup_path),
        ),
        migrations.AddField(
            model_name='setup',
            name='config_race',
            field=models.FileField(blank=True, null=True, upload_to=catalogo.models.upload_setup_path),
        ),
        migrations.AddField(
            model_name='setup',
            name='config_race_rain',
            field=models.FileField(blank=True, null=True, upload_to=catalogo.models.upload_setup_path),
        ),
        migrations.AddField(
            model_name='setup',
            name='config_race_safe',
            field=models.FileField(blank=True, null=True, upload_to=catalogo.models.upload_setup_path),
        ),
        migrations.AddField(
            model_name='setup',
            name='nome_versao',
            field=models.CharField(default='Versão Inicial', max_length=50),
        ),
        migrations.AddField(
            model_name='setup',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meus_setups_privados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setup',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups_privados', to='catalogo.carro'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='pista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups_privados', to='catalogo.pista'),
        ),
        migrations.CreateModel(
            name='SetupPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_versao', models.CharField(default='Versão Inicial', max_length=50)),
                ('config_qualy_safe', models.FileField(blank=True, null=True, upload_to=catalogo.models.upload_setup_path)),
                ('config_qualy', models.FileField(blank=True, null=True, upload_to=catalogo.models.upload_setup_path)),
                ('config_qualy_rain', models.FileField(blank=True, null=True, upload_to=catalogo.models.upload_setup_path)),
                ('config_race_safe', models.FileField(blank=True, null=True, upload_to=catalogo.models.upload_setup_path)),
                ('config_race', models.FileField(blank=True, null=True, upload_to=catalogo.models.upload_setup_path)),
                ('config_race_rain', models.FileField(blank=True, null=True, upload_to=catalogo.models.upload_setup_path)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups_publicos', to='catalogo.carro')),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups_publicos', to='catalogo.pista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_setups_publicos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
