# Generated by Django 6.0.3 on 2026-03-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_remove_setup_arquivo_remove_setup_nome_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
