# Generated by Django 6.0.3 on 2026-03-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_setup_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='setuppublico',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setuppublico',
            name='tipo',
            field=models.CharField(choices=[('S', 'Sprint (Corridas Curtas)'), ('E', 'Endurance (Corridas Longas)')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='setuppublico',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
